# Generated by Django 4.0.dev20210401123330 on 2022-01-03 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='temperature',
        ),
    ]
