# Generated by Django 4.0.dev20210401123330 on 2022-01-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_email_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
