# Generated by Django 4.0.dev20210401123330 on 2022-01-03 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_alter_email_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='time',
        ),
    ]
