# Generated by Django 4.0.dev20210401123330 on 2022-01-03 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_remove_email_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
