# Generated by Django 4.0.dev20210401123330 on 2022-01-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_remove_email_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='temperature',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
