# Generated by Django 4.0.dev20210401123330 on 2022-01-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_email_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='temperature',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
