# Generated by Django 4.0.dev20210401123330 on 2022-01-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0010_alter_email_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='temperature',
        ),
    ]
