# Generated by Django 4.0.dev20210401123330 on 2022-01-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0011_remove_email_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='city',
            field=models.CharField(choices=[('mumbai', 'mumbai'), ('delhi', 'delhi'), ('chennai', 'chennai'), ('bangalore', 'bangalore'), ('kolkata', 'kolkata')], max_length=100, null=True),
        ),
    ]
